kind: pipeline
name: default

steps:
- name: MVN Compile、Package、Publish To MVN Repository.
  image: cnlym/maven:3-jdk-11-alpine-aliyun
  commands:
  - cd plugins/errcode-maven-plugin
  # Active mvn package plugins for higher quality jar files.
  - sed -i 's#<phase>deploy</phase><!-- ACTIVE_WITH_verify -->#<phase>verify</phase><!-- ACTIVE_WITH_verify -->#g' pom.xml
  - sed -i 's#<phase>deploy</phase><!-- ACTIVE_WITH_package -->#<phase>package</phase><!-- ACTIVE_WITH_package -->#g' pom.xml
  - mvn deploy -P release -Dmaven.test.skip=true -V
  - echo 'FINISHED deploy!'

- name: Build Notification. --- with DingTalk
  image: guoxudongdocker/drone-dingtalk
  settings:
    token: 178f267b9b16b168e0a0afb223b3d41f3a58e62180ab5288aa576db02965dd72
    type: markdown

trigger:
  branch:
  - master    
  event:
  - push
