kind: pipeline
name: default

steps:
- name: 编译、打包、发布到 maven 仓库
  image: cnlym/maven:3-jdk-11-alpine-aliyun
  commands:
  - cd plugins/errcode-maven-plugin
  - sed -i 's#<phase>deploy</phase><!-- gpg phase verify deploy -->#<phase>verify</phase><!-- gpg phase verify deploy -->#g' pom.xml
  - mvn deploy -P release -Dmaven.test.skip=true -V
  - echo 'FINISHED deploy!'

- name: 钉钉通知、微信通知构建结果
  image: guoxudongdocker/drone-dingtalk
  settings:
    token: 5f6c32b36e771df227b1ccb8898325158e12d851ae61982d1ec225a1aa58e251
    type: markdown

trigger:
  branch:
  - master    
  event:
  - push
