kind: pipeline
name: default

steps:
- name: MVN Compile、Package、Publish To MVN Repository.
  image: cnlym/maven:3-jdk-21-alpine-aliyun
  # 加速，对于这种稳定的容器
  pull: if-not-exists
  commands:
#  - gpg --import priv.key.lym
  - /root/drone_ding_notify_curl.sh
  - cd plugins/errcode-maven-plugin
  # Active mvn package plugins for higher quality jar files.
  - sed -i 's#<phase>deploy</phase><!-- ACTIVE_WITH_verify -->#<phase>verify</phase><!-- ACTIVE_WITH_verify -->#g' pom.xml
  - sed -i 's#<phase>deploy</phase><!-- ACTIVE_WITH_package -->#<phase>package</phase><!-- ACTIVE_WITH_package -->#g' pom.xml
  #- mvn install -P release -Dmaven.test.skip=true -V
  - mvn deploy -P release -Dmaven.test.skip=true -V
  - echo 'FINISHED deploy!'

- name: Build Notification. --- with DingTalk
  image: guoxudongdocker/drone-dingtalk
  settings:
    token:
      from_secret: ding_token
    type: markdown

trigger:
  branch:
  - master    
  event:
  - push
